language: ruby
cache: bundler
env:
  global:
    - DATABASE_URL=postgresql://localhost/travis_ci_test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec
deploy:
  provider: heroku
  api_key: $HEROKU_PRODUCTION_KEY
  app: $HEROKU_APP_NAME
  run: "rake db:migrate"
