language: ruby
cache: bundler
env:
  global:
    - DATABASE_URL=postgresql://localhost/travis_ci_test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec