# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7231d52d855014fa5c8c238c0dfdc9108ac13de96b2d46cf8fedbfd588adc1c13e89e9361accf19b5a1c8f212f7a007d9ae35b1fdd076dc94f9f34b2c30fd683

test:
  secret_key_base: 609161ebcfb42867ce6ff6f9e096211b24e5d05430d57bf6ebda0eee58655abb9c41fce1b7503730513866fdd9f617aa099cae781316d410e8a8cbdd8c9a1d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
